__author__="keghol"

import os
import subprocess


version_msg = "# Do not edit this file"
with open(version_py, 'wt') as fh:
    fh.write("{}{}__version__={}".format(version_msg, os.linesep, version_git))

def get_version_from_git():
    try:
        p = subprocess.Popen(['git', 'describe'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
        o = p.communicate()
        if p.returncode != 0:
            raise Exception('git describe failed to execute reason: %s' % o[1])
        return o[0].rstrip()

    except Exception:
        print("no tags exist")
