__author__="keghol"

# this should only be used from the top-level of your project, where it will
# create a version.py file with the corresponding version

import os
import subprocess

version_py = os.path.join(os.path.dirname(__file__), 'version.py')
version_msg = "# Do not edit this file"

def get_version_from_git():
    version = None
    try:
        p = subprocess.Popen(['git', 'describe'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
        o = p.communicate()
        if p.returncode != 0:
            raise Exception('git describe failed to execute reason: %s' % o[1])
        version = o[0].rstrip()

    except Exception:
        print("no tags exist")

    with open(version_py, 'wt') as fh:
        fh.write("{}{}__version__={}".format(version_msg, os.linesep, version))

    return version
